-- Must run in SQLCMD.

--:connect RPTSVR01 

go
use msdb
go
SELECT ','''+NAME+''' `' SSRS FROM SYSJOBS J WHERE LEN(NAME)=36 ORDER  BY 1
go
SELECT ','''+NAME+''' `' NonSSRS FROM SYSJOBS J WHERE LEN(NAME)<>36 ORDER  BY 1
go