-- Must run in SQLCMD.

:connect FLDSVRSQL03
go
use msdb
go
SELECT ','''+NAME+''' `' SSRS FROM SYSJOBS J WHERE LEN(NAME)=36 ORDER  BY 1
go
SELECT ','''+NAME+''' `' NonSSRS FROM SYSJOBS J WHERE LEN(NAME)<>36 ORDER  BY 1
go